package org.jaudiotagger.tag.vorbiscomment;

import java.util.EnumSet;
import org.jaudiotagger.audio.asf.data.ContentDescription;
import org.jaudiotagger.tag.id3.framebody.FrameBodyTXXX;
import org.jaudiotagger.tag.reference.Tagger;

/* loaded from: classes3.dex */
public enum VorbisCommentFieldKey {
    ACOUSTID_FINGERPRINT("ACOUSTID_FINGERPRINT", EnumSet.of(Tagger.PICARD)),
    ACOUSTID_ID("ACOUSTID_ID", EnumSet.of(Tagger.PICARD)),
    ALBUM("ALBUM", EnumSet.of(Tagger.XIPH, Tagger.PICARD, Tagger.JAIKOZ, Tagger.ROON)),
    ALBUMARTIST("ALBUMARTIST", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    ALBUMARTISTSORT("ALBUMARTISTSORT", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    ALBUMARTISTS(FrameBodyTXXX.ALBUM_ARTISTS, EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    ALBUMARTISTSSORT(FrameBodyTXXX.ALBUM_ARTISTS_SORT, EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    ALBUMARTIST_JRIVER(FrameBodyTXXX.ALBUM_ARTIST, EnumSet.of(Tagger.JRIVER)),
    ALBUMSORT("ALBUMSORT", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    ALBUM_ARTIST("ALBUM_ARTIST", EnumSet.of(Tagger.MEDIA_MONKEY)),
    ALBUM_YEAR(FrameBodyTXXX.ALBUM_YEAR, EnumSet.of(Tagger.JAIKOZ)),
    ARRANGER(FrameBodyTXXX.ARRANGER, EnumSet.of(Tagger.PICARD)),
    ARRANGER_SORT(FrameBodyTXXX.ARRANGER_SORT, EnumSet.of(Tagger.JAIKOZ)),
    ARTIST("ARTIST", EnumSet.of(Tagger.XIPH, Tagger.PICARD, Tagger.JAIKOZ)),
    ARTISTS(FrameBodyTXXX.ARTISTS, EnumSet.of(Tagger.JAIKOZ)),
    ARTISTSORT("ARTISTSORT", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    ARTISTS_SORT(FrameBodyTXXX.ARTISTS_SORT, EnumSet.of(Tagger.JAIKOZ)),
    AUDIO_ENGINEER(FrameBodyTXXX.AUDIO_ENGINEER, EnumSet.of(Tagger.SONGKONG)),
    AUDIO_ENGINEER_SORT(FrameBodyTXXX.AUDIO_ENGINEER_SORT, EnumSet.of(Tagger.SONGKONG)),
    ASIN(FrameBodyTXXX.AMAZON_ASIN, EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    BALANCE_ENGINEER(FrameBodyTXXX.BALANCE_ENGINEER, EnumSet.of(Tagger.SONGKONG)),
    BALANCE_ENGINEER_SORT(FrameBodyTXXX.BALANCE_ENGINEER_SORT, EnumSet.of(Tagger.SONGKONG)),
    BARCODE(FrameBodyTXXX.BARCODE, EnumSet.of(Tagger.JAIKOZ, Tagger.ROON)),
    BPM("BPM", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    CATALOGNUMBER(FrameBodyTXXX.CATALOG_NO, EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    CHOIR(FrameBodyTXXX.CHOIR, EnumSet.of(Tagger.JAIKOZ)),
    CHOIR_SORT(FrameBodyTXXX.CHOIR_SORT, EnumSet.of(Tagger.JAIKOZ)),
    CLASSICAL_CATALOG(FrameBodyTXXX.CLASSICAL_CATALOG, EnumSet.of(Tagger.JAIKOZ)),
    CLASSICAL_NICKNAME(FrameBodyTXXX.CLASSICAL_NICKNAME, EnumSet.of(Tagger.JAIKOZ)),
    COMMENT("COMMENT", EnumSet.of(Tagger.PICARD)),
    COMPILATION("COMPILATION", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    COMPOSER("COMPOSER", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ, Tagger.ROON)),
    COMPOSERSORT("COMPOSERSORT", EnumSet.of(Tagger.JAIKOZ)),
    CONDUCTOR("CONDUCTOR", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ, Tagger.ROON)),
    CONDUCTOR_SORT(FrameBodyTXXX.CONDUCTOR_SORT, EnumSet.of(Tagger.JAIKOZ)),
    CONTACT("CONTACT", EnumSet.of(Tagger.XIPH)),
    COPYRIGHT(ContentDescription.KEY_COPYRIGHT, EnumSet.of(Tagger.XIPH, Tagger.PICARD, Tagger.JAIKOZ)),
    COUNTRY("COUNTRY", EnumSet.of(Tagger.PICARD)),
    COVERART("COVERART", EnumSet.of(Tagger.JAIKOZ)),
    COVERARTMIME("COVERARTMIME", EnumSet.of(Tagger.JAIKOZ)),
    CREDITS(FrameBodyTXXX.CREDITS, EnumSet.of(Tagger.SONGKONG)),
    CUSTOM1("CUSTOM1", EnumSet.of(Tagger.MEDIA_MONKEY)),
    CUSTOM2("CUSTOM2", EnumSet.of(Tagger.MEDIA_MONKEY)),
    CUSTOM3("CUSTOM3", EnumSet.of(Tagger.MEDIA_MONKEY)),
    CUSTOM4("CUSTOM4", EnumSet.of(Tagger.MEDIA_MONKEY)),
    CUSTOM5("CUSTOM5", EnumSet.of(Tagger.MEDIA_MONKEY)),
    DATE("DATE", EnumSet.of(Tagger.XIPH, Tagger.PICARD, Tagger.JAIKOZ)),
    DESCRIPTION(ContentDescription.KEY_DESCRIPTION, EnumSet.of(Tagger.XIPH)),
    DISCNUMBER("DISCNUMBER", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    DISCSUBTITLE("DISCSUBTITLE", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    DISCTOTAL("DISCTOTAL", EnumSet.of(Tagger.XIPH, Tagger.PICARD)),
    DJMIXER(FrameBodyTXXX.DJMIXER, EnumSet.of(Tagger.PICARD)),
    DJMIXER_SORT(FrameBodyTXXX.DJMIXER_SORT, EnumSet.of(Tagger.SONGKONG)),
    ENCODEDBY("ENCODEDBY", EnumSet.of(Tagger.PICARD)),
    ENCODER("ENCODER"),
    ENGINEER(FrameBodyTXXX.ENGINEER, EnumSet.of(Tagger.PICARD, Tagger.ROON)),
    ENGINEER_SORT(FrameBodyTXXX.ENGINEER_SORT, EnumSet.of(Tagger.SONGKONG)),
    ENSEMBLE(FrameBodyTXXX.ENSEMBLE, EnumSet.of(Tagger.MEDIA_MONKEY, Tagger.JAIKOZ, Tagger.ROON)),
    ENSEMBLE_SORT(FrameBodyTXXX.ENSEMBLE_SORT, EnumSet.of(Tagger.JAIKOZ)),
    FBPM(FrameBodyTXXX.FBPM, EnumSet.of(Tagger.BEATUNES)),
    GENRE("GENRE", EnumSet.of(Tagger.XIPH, Tagger.PICARD, Tagger.JAIKOZ)),
    GROUP(FrameBodyTXXX.GROUP, EnumSet.of(Tagger.JAIKOZ, Tagger.MINIMSERVER)),
    GROUPING("GROUPING", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    INSTRUMENT(FrameBodyTXXX.INSTRUMENT, EnumSet.of(Tagger.JAIKOZ)),
    INVOLVEDPEOPLE("INVOLVEDPEOPLE", EnumSet.of(Tagger.ROON)),
    IPI(FrameBodyTXXX.IPI, EnumSet.of(Tagger.JAIKOZ)),
    ISRC("ISRC", EnumSet.of(Tagger.XIPH, Tagger.PICARD, Tagger.JAIKOZ)),
    ISWC(FrameBodyTXXX.ISWC, EnumSet.of(Tagger.XIPH, Tagger.PICARD, Tagger.JAIKOZ)),
    IS_CLASSICAL(FrameBodyTXXX.IS_CLASSICAL, EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    IS_GREATEST_HITS(FrameBodyTXXX.IS_GREATEST_HITS, EnumSet.of(Tagger.JAIKOZ)),
    IS_HD(FrameBodyTXXX.IS_HD, EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    IS_LIVE(FrameBodyTXXX.LIVE, EnumSet.of(Tagger.ROON)),
    IS_SOUNDTRACK(FrameBodyTXXX.IS_SOUNDTRACK, EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    JAIKOZ_ID(FrameBodyTXXX.JAIKOZ_ID, EnumSet.of(Tagger.JAIKOZ)),
    KEY("KEY"),
    LABEL("LABEL", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ, Tagger.ROON)),
    LANGUAGE("LANGUAGE"),
    LICENSE("LICENSE", EnumSet.of(Tagger.XIPH)),
    LOCATION("LOCATION", EnumSet.of(Tagger.XIPH)),
    LYRICIST("LYRICIST", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ, Tagger.ROON)),
    LYRICIST_SORT(FrameBodyTXXX.LYRICIST_SORT, EnumSet.of(Tagger.JAIKOZ)),
    LYRICS("LYRICS", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    MEDIA("MEDIA", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    MASTERING(FrameBodyTXXX.MASTERING, EnumSet.of(Tagger.SONGKONG)),
    MASTERING_SORT(FrameBodyTXXX.MASTERING_SORT, EnumSet.of(Tagger.SONGKONG)),
    METADATA_BLOCK_PICTURE("METADATA_BLOCK_PICTURE", EnumSet.of(Tagger.XIPH)),
    MIXER(FrameBodyTXXX.MIXER, EnumSet.of(Tagger.PICARD)),
    MIXER_SORT(FrameBodyTXXX.MIXER_SORT, EnumSet.of(Tagger.SONGKONG)),
    MOOD(FrameBodyTXXX.MOOD, EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    MOOD_ACOUSTIC(FrameBodyTXXX.MOOD_ACOUSTIC, EnumSet.of(Tagger.JAIKOZ)),
    MOOD_AGGRESSIVE(FrameBodyTXXX.MOOD_AGGRESSIVE, EnumSet.of(Tagger.JAIKOZ)),
    MOOD_AROUSAL(FrameBodyTXXX.MOOD_AROUSAL, EnumSet.of(Tagger.JAIKOZ)),
    MOOD_DANCEABILITY(FrameBodyTXXX.MOOD_DANCEABILITY, EnumSet.of(Tagger.JAIKOZ)),
    MOOD_ELECTRONIC(FrameBodyTXXX.MOOD_ELECTRONIC, EnumSet.of(Tagger.JAIKOZ)),
    MOOD_HAPPY(FrameBodyTXXX.MOOD_HAPPY, EnumSet.of(Tagger.JAIKOZ)),
    MOOD_INSTRUMENTAL(FrameBodyTXXX.MOOD_INSTRUMENTAL, EnumSet.of(Tagger.JAIKOZ)),
    MOOD_PARTY(FrameBodyTXXX.MOOD_PARTY, EnumSet.of(Tagger.JAIKOZ)),
    MOOD_RELAXED(FrameBodyTXXX.MOOD_RELAXED, EnumSet.of(Tagger.JAIKOZ)),
    MOOD_SAD(FrameBodyTXXX.MOOD_SAD, EnumSet.of(Tagger.JAIKOZ)),
    MOOD_VALENCE(FrameBodyTXXX.MOOD_VALENCE, EnumSet.of(Tagger.JAIKOZ)),
    MOVEMENT("MOVEMENT", EnumSet.of(Tagger.JAIKOZ)),
    MOVEMENT_NO("MOVEMENT_NO", EnumSet.of(Tagger.JAIKOZ)),
    MOVEMENT_TOTAL("MOVEMENT_TOTAL", EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_ALBUMARTISTID("MUSICBRAINZ_ALBUMARTISTID", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    MUSICBRAINZ_ALBUMID("MUSICBRAINZ_ALBUMID", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    MUSICBRAINZ_ALBUMSTATUS("MUSICBRAINZ_ALBUMSTATUS", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    MUSICBRAINZ_ALBUMTYPE("MUSICBRAINZ_ALBUMTYPE", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    MUSICBRAINZ_ARTISTID("MUSICBRAINZ_ARTISTID", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    MUSICBRAINZ_DISCID("MUSICBRAINZ_DISCID", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    MUSICBRAINZ_ORIGINAL_ALBUMID("MUSICBRAINZ_ORIGINALALBUMID", EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_RELEASEGROUPID("MUSICBRAINZ_RELEASEGROUPID", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    MUSICBRAINZ_RELEASETRACKID("MUSICBRAINZ_RELEASETRACKID", EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_TRACKID("MUSICBRAINZ_TRACKID", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK(FrameBodyTXXX.MUSICBRAINZ_WORK, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORKID("MUSICBRAINZ_WORKID", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    MUSICBRAINZ_RECORDING_WORK(FrameBodyTXXX.MUSICBRAINZ_RECORDING_WORK, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_RECORDING_WORK_ID(FrameBodyTXXX.MUSICBRAINZ_RECORDING_WORK_ID, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL1(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL1, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL1_ID(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL1_ID, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL1_TYPE(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL1_TYPE, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL2(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL2, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL2_ID(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL2_ID, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL2_TYPE(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL2_TYPE, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL3(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL3, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL3_ID(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL3_ID, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL3_TYPE(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL3_TYPE, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL4_ID(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL4_ID, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL4(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL4, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL4_TYPE(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL4_TYPE, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL5(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL5, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL5_ID(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL5_ID, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL5_TYPE(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL5_TYPE, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL6(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL6, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL6_ID(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL6_ID, EnumSet.of(Tagger.JAIKOZ)),
    MUSICBRAINZ_WORK_PART_LEVEL6_TYPE(FrameBodyTXXX.MUSICBRAINZ_WORK_PART_LEVEL6_TYPE, EnumSet.of(Tagger.JAIKOZ)),
    MUSICIAN("MUSICIAN", EnumSet.of(Tagger.JAIKOZ)),
    MUSICIP_PUID("MUSICIP_PUID", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    OCCASION("OCCASION", EnumSet.of(Tagger.MEDIA_MONKEY)),
    OPUS("OPUS", EnumSet.of(Tagger.JAIKOZ)),
    ORCHESTRA(FrameBodyTXXX.ORCHESTRA, EnumSet.of(Tagger.JAIKOZ)),
    ORCHESTRA_SORT(FrameBodyTXXX.ORCHESTRA_SORT, EnumSet.of(Tagger.JAIKOZ)),
    ORGANIZATION("ORGANIZATION", EnumSet.of(Tagger.XIPH)),
    ORIGINAL_ALBUM("ORIGINAL ALBUM", EnumSet.of(Tagger.JAIKOZ, Tagger.MEDIA_MONKEY)),
    ORIGINALRELEASEDATE(FrameBodyTXXX.ORIGINALRELEASEDATE, EnumSet.of(Tagger.ROON)),
    ORIGINAL_ARTIST("ORIGINAL ARTIST", EnumSet.of(Tagger.JAIKOZ, Tagger.MEDIA_MONKEY)),
    ORIGINAL_LYRICIST("ORIGINAL LYRICIST", EnumSet.of(Tagger.MEDIA_MONKEY)),
    ORIGINAL_YEAR("ORIGINAL YEAR", EnumSet.of(Tagger.JAIKOZ, Tagger.MEDIA_MONKEY)),
    OVERALL_WORK(FrameBodyTXXX.OVERALL_WORK, EnumSet.of(Tagger.JAIKOZ)),
    PART(FrameBodyTXXX.PART, EnumSet.of(Tagger.JAIKOZ, Tagger.ROON)),
    PART_NUMBER(FrameBodyTXXX.PART_NUMBER, EnumSet.of(Tagger.XIPH)),
    PART_TYPE(FrameBodyTXXX.PART_TYPE, EnumSet.of(Tagger.JAIKOZ)),
    PERFORMER(FrameBodyTXXX.PERFORMER, EnumSet.of(Tagger.XIPH, Tagger.PICARD)),
    PERFORMER_NAME(FrameBodyTXXX.PERFORMER_NAME, EnumSet.of(Tagger.JAIKOZ)),
    PERFORMER_NAME_SORT(FrameBodyTXXX.PERFORMER_NAME_SORT, EnumSet.of(Tagger.JAIKOZ)),
    PERIOD(FrameBodyTXXX.PERIOD, EnumSet.of(Tagger.MUSICHI)),
    PRODUCER(FrameBodyTXXX.PRODUCER, EnumSet.of(Tagger.PICARD, Tagger.ROON)),
    PRODUCER_SORT(FrameBodyTXXX.PRODUCER_SORT, EnumSet.of(Tagger.SONGKONG)),
    PRODUCTNUMBER("PRODUCTNUMBER", EnumSet.of(Tagger.XIPH)),
    QUALITY("QUALITY", EnumSet.of(Tagger.MEDIA_MONKEY)),
    RANKING(FrameBodyTXXX.RANKING, EnumSet.of(Tagger.JAIKOZ)),
    RATING(ContentDescription.KEY_RATING, EnumSet.of(Tagger.MEDIA_MONKEY)),
    RECORDING_ENGINEER("RECORIDNG_ENGINEER", EnumSet.of(Tagger.SONGKONG)),
    RECORDING_ENGINEER_SORT(FrameBodyTXXX.RECORDING_ENGINEER_SORT, EnumSet.of(Tagger.SONGKONG)),
    RECORDINGDATE(FrameBodyTXXX.RECORDINGDATE, EnumSet.of(Tagger.ROON)),
    RECORDINGSTARTDATE(FrameBodyTXXX.RECORDINGSTARTDATE, EnumSet.of(Tagger.ROON)),
    RECORDINGENDDATE(FrameBodyTXXX.RECORDINGENDDATE, EnumSet.of(Tagger.ROON)),
    RECORDINGLOCATION(FrameBodyTXXX.RECORDINGLOCATION, EnumSet.of(Tagger.ROON)),
    RELEASECOUNTRY("RELEASECOUNTRY", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    REMIXER(FrameBodyTXXX.REMIXER, EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    ROONALBUMTAG(FrameBodyTXXX.ROONALBUMTAG, EnumSet.of(Tagger.ROON)),
    ROONTRACKTAG(FrameBodyTXXX.ROONTRACKTAG, EnumSet.of(Tagger.ROON)),
    SCRIPT(FrameBodyTXXX.SCRIPT, EnumSet.of(Tagger.JAIKOZ)),
    SECTION(FrameBodyTXXX.SECTION, EnumSet.of(Tagger.ROON)),
    SINGLE_DISC_TRACK_NO(FrameBodyTXXX.SINGLE_DISC_TRACK_NO, EnumSet.of(Tagger.JAIKOZ)),
    SONGKONG_ID(FrameBodyTXXX.SONGKONG_ID, EnumSet.of(Tagger.SONGKONG)),
    SOUND_ENGINEER(FrameBodyTXXX.SOUND_ENGINEER, EnumSet.of(Tagger.SONGKONG)),
    SOUND_ENGINEER_SORT("SOUNDO_ENGINEER_SORT", EnumSet.of(Tagger.SONGKONG)),
    SOURCEMEDIA("SOURCEMEDIA", EnumSet.of(Tagger.XIPH)),
    SUBTITLE("SUBTITLE", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    TAGS(FrameBodyTXXX.TAGS, EnumSet.of(Tagger.JAIKOZ)),
    TEMPO("TEMPO", EnumSet.of(Tagger.MEDIA_MONKEY)),
    TIMBRE(FrameBodyTXXX.TIMBRE, EnumSet.of(Tagger.JAIKOZ)),
    TITLE(ContentDescription.KEY_TITLE, EnumSet.of(Tagger.XIPH, Tagger.PICARD, Tagger.JAIKOZ, Tagger.ROON)),
    TITLE_MOVEMENT(FrameBodyTXXX.TITLE_MOVEMENT, EnumSet.of(Tagger.JAIKOZ)),
    TITLESORT("TITLESORT", EnumSet.of(Tagger.PICARD, Tagger.JAIKOZ)),
    TONALITY(FrameBodyTXXX.TONALITY, EnumSet.of(Tagger.JAIKOZ)),
    TRACKNUMBER("TRACKNUMBER", EnumSet.of(Tagger.XIPH, Tagger.PICARD, Tagger.JAIKOZ)),
    TRACKTOTAL("TRACKTOTAL", EnumSet.of(Tagger.XIPH, Tagger.PICARD)),
    URL_BANDCAMP_ARTIST_SITE("URL_BANDCAMP_ARTIST_SITE", EnumSet.of(Tagger.SONGKONG)),
    URL_BANDCAMP_RELEASE_SITE("URL_BANDCAMP_RELEASE_SITE", EnumSet.of(Tagger.SONGKONG)),
    URL_DISCOGS_ARTIST_SITE("URL_DISCOGS_ARTIST_SITE", EnumSet.of(Tagger.JAIKOZ)),
    URL_DISCOGS_RELEASE_SITE("URL_DISCOGS_RELEASE_SITE", EnumSet.of(Tagger.JAIKOZ)),
    URL_LYRICS_SITE("URL_LYRICS_SITE", EnumSet.of(Tagger.JAIKOZ)),
    URL_OFFICIAL_ARTIST_SITE("URL_OFFICIAL_ARTIST_SITE", EnumSet.of(Tagger.JAIKOZ)),
    URL_OFFICIAL_RELEASE_SITE("URL_OFFICIAL_RELEASE_SITE", EnumSet.of(Tagger.JAIKOZ)),
    URL_WIKIPEDIA_ARTIST_SITE("URL_WIKIPEDIA_ARTIST_SITE", EnumSet.of(Tagger.JAIKOZ)),
    URL_WIKIPEDIA_RELEASE_SITE("URL_WIKIPEDIA_RELEASE_SITE", EnumSet.of(Tagger.JAIKOZ)),
    VENDOR("VENDOR"),
    VERSION(FrameBodyTXXX.VERSION, EnumSet.of(Tagger.XIPH, Tagger.ROON)),
    WORK(FrameBodyTXXX.WORK, EnumSet.of(Tagger.JAIKOZ)),
    WORK_TYPE(FrameBodyTXXX.WORK_TYPE, EnumSet.of(Tagger.JAIKOZ));

    private String fieldName;
    private String realFieldName;
    private EnumSet<Tagger> taggers;

    VorbisCommentFieldKey(String str) {
        this.fieldName = str;
    }

    VorbisCommentFieldKey(String str, EnumSet enumSet) {
        this.fieldName = str;
        this.taggers = enumSet;
    }

    VorbisCommentFieldKey(String str, String str2) {
        this.fieldName = str;
        this.realFieldName = str2;
    }

    VorbisCommentFieldKey(String str, String str2, EnumSet enumSet) {
        this.fieldName = str;
        this.realFieldName = str2;
        this.taggers = enumSet;
    }

    public String getFieldName() {
        return this.fieldName;
    }

    public String getRealFieldName() {
        return this.realFieldName;
    }

    public EnumSet<Tagger> getTaggers() {
        return this.taggers;
    }
}
