package org.jaudiotagger.tag.id3;

import java.util.EnumMap;
import java.util.Iterator;
import java.util.Map;
import org.jaudiotagger.tag.FieldKey;
import org.jaudiotagger.tag.datatype.DataTypes;

/* loaded from: classes3.dex */
public class ID3v24Frames extends ID3Frames {
    public static final String FRAME_ID_ACCOMPANIMENT = "TPE2";
    public static final String FRAME_ID_ALBUM = "TALB";
    public static final String FRAME_ID_ALBUM_ARTIST_SORT_ORDER_ITUNES = "TSO2";
    public static final String FRAME_ID_ALBUM_SORT_ORDER = "TSOA";
    public static final String FRAME_ID_ARTIST = "TPE1";
    public static final String FRAME_ID_ARTIST_SORT_ORDER = "TSOP";
    public static final String FRAME_ID_ATTACHED_PICTURE = "APIC";
    public static final String FRAME_ID_AUDIO_ENCRYPTION = "AENC";
    public static final String FRAME_ID_AUDIO_SEEK_POINT_INDEX = "ASPI";
    public static final String FRAME_ID_BPM = "TBPM";
    public static final String FRAME_ID_CHAPTER = "CHAP";
    public static final String FRAME_ID_CHAPTER_TOC = "CTOC";
    public static final String FRAME_ID_COMMENT = "COMM";
    public static final String FRAME_ID_COMMERCIAL_FRAME = "COMR";
    public static final String FRAME_ID_COMPOSER = "TCOM";
    public static final String FRAME_ID_COMPOSER_SORT_ORDER_ITUNES = "TSOC";
    public static final String FRAME_ID_CONDUCTOR = "TPE3";
    public static final String FRAME_ID_CONTENT_GROUP_DESC = "TIT1";
    public static final String FRAME_ID_COPYRIGHTINFO = "TCOP";
    public static final String FRAME_ID_ENCODEDBY = "TENC";
    public static final String FRAME_ID_ENCODING_TIME = "TDEN";
    public static final String FRAME_ID_ENCRYPTION = "ENCR";
    public static final String FRAME_ID_EQUALISATION2 = "EQU2";
    public static final String FRAME_ID_EVENT_TIMING_CODES = "ETCO";
    public static final String FRAME_ID_FILE_OWNER = "TOWN";
    public static final String FRAME_ID_FILE_TYPE = "TFLT";
    public static final String FRAME_ID_GENERAL_ENCAPS_OBJECT = "GEOB";
    public static final String FRAME_ID_GENRE = "TCON";
    public static final String FRAME_ID_GROUP_ID_REG = "GRID";
    public static final String FRAME_ID_HW_SW_SETTINGS = "TSSE";
    public static final String FRAME_ID_INITIAL_KEY = "TKEY";
    public static final String FRAME_ID_INVOLVED_PEOPLE = "TIPL";
    public static final String FRAME_ID_ISRC = "TSRC";
    public static final String FRAME_ID_IS_COMPILATION = "TCMP";
    public static final String FRAME_ID_ITUNES_GROUPING = "GRP1";
    public static final String FRAME_ID_LANGUAGE = "TLAN";
    public static final String FRAME_ID_LENGTH = "TLEN";
    public static final String FRAME_ID_LINKED_INFO = "LINK";
    public static final String FRAME_ID_LYRICIST = "TEXT";
    public static final String FRAME_ID_MEDIA_TYPE = "TMED";
    public static final String FRAME_ID_MOOD = "TMOO";
    public static final String FRAME_ID_MOVEMENT = "MVNM";
    public static final String FRAME_ID_MOVEMENT_NO = "MVIN";
    public static final String FRAME_ID_MPEG_LOCATION_LOOKUP_TABLE = "MLLT";
    public static final String FRAME_ID_MUSICIAN_CREDITS = "TMCL";
    public static final String FRAME_ID_MUSIC_CD_ID = "MCDI";
    public static final String FRAME_ID_ORIGARTIST = "TOPE";
    public static final String FRAME_ID_ORIGINAL_RELEASE_TIME = "TDOR";
    public static final String FRAME_ID_ORIG_FILENAME = "TOFN";
    public static final String FRAME_ID_ORIG_LYRICIST = "TOLY";
    public static final String FRAME_ID_ORIG_TITLE = "TOAL";
    public static final String FRAME_ID_OWNERSHIP = "OWNE";
    public static final String FRAME_ID_PERFORMER_SORT_OWNER = "TSOP";
    public static final String FRAME_ID_PLAYLIST_DELAY = "TDLY";
    public static final String FRAME_ID_PLAY_COUNTER = "PCNT";
    public static final String FRAME_ID_POPULARIMETER = "POPM";
    public static final String FRAME_ID_POSITION_SYNC = "POSS";
    public static final String FRAME_ID_PRIVATE = "PRIV";
    public static final String FRAME_ID_PRODUCED_NOTICE = "TPRO";
    public static final String FRAME_ID_PUBLISHER = "TPUB";
    public static final String FRAME_ID_RADIO_NAME = "TRSN";
    public static final String FRAME_ID_RADIO_OWNER = "TRSO";
    public static final String FRAME_ID_RECOMMENDED_BUFFER_SIZE = "RBUF";
    public static final String FRAME_ID_RELATIVE_VOLUME_ADJUSTMENT2 = "RVA2";
    public static final String FRAME_ID_RELEASE_TIME = "TDRL";
    public static final String FRAME_ID_REMIXED = "TPE4";
    public static final String FRAME_ID_REVERB = "RVRB";
    public static final String FRAME_ID_SEEK = "SEEK";
    public static final String FRAME_ID_SET = "TPOS";
    public static final String FRAME_ID_SET_SUBTITLE = "TSST";
    public static final String FRAME_ID_SIGNATURE = "SIGN";
    public static final String FRAME_ID_SYNC_LYRIC = "SYLT";
    public static final String FRAME_ID_SYNC_TEMPO = "SYTC";
    public static final String FRAME_ID_TAGGING_TIME = "TDTG";
    public static final String FRAME_ID_TERMS_OF_USE = "USER";
    public static final String FRAME_ID_TITLE = "TIT2";
    public static final String FRAME_ID_TITLE_REFINEMENT = "TIT3";
    public static final String FRAME_ID_TITLE_SORT_ORDER = "TSOT";
    public static final String FRAME_ID_TITLE_SORT_OWNER = "TSOT";
    public static final String FRAME_ID_TRACK = "TRCK";
    public static final String FRAME_ID_UNIQUE_FILE_ID = "UFID";
    public static final String FRAME_ID_UNSYNC_LYRICS = "USLT";
    public static final String FRAME_ID_URL_ARTIST_WEB = "WOAR";
    public static final String FRAME_ID_URL_COMMERCIAL = "WCOM";
    public static final String FRAME_ID_URL_COPYRIGHT = "WCOP";
    public static final String FRAME_ID_URL_FILE_WEB = "WOAF";
    public static final String FRAME_ID_URL_OFFICIAL_RADIO = "WORS";
    public static final String FRAME_ID_URL_PAYMENT = "WPAY";
    public static final String FRAME_ID_URL_PUBLISHERS = "WPUB";
    public static final String FRAME_ID_URL_SOURCE_WEB = "WOAS";
    public static final String FRAME_ID_USER_DEFINED_INFO = "TXXX";
    public static final String FRAME_ID_USER_DEFINED_URL = "WXXX";
    public static final String FRAME_ID_YEAR = "TDRC";
    private static ID3v24Frames id3v24Frames;
    protected EnumMap<FieldKey, ID3v24FieldKey> tagFieldToId3 = new EnumMap<>(FieldKey.class);
    protected EnumMap<ID3v24FieldKey, FieldKey> id3ToTagField = new EnumMap<>(ID3v24FieldKey.class);

    public static ID3v24Frames getInstanceOf() {
        if (id3v24Frames == null) {
            id3v24Frames = new ID3v24Frames();
        }
        return id3v24Frames;
    }

    private ID3v24Frames() {
        this.supportedFrames.add("TPE2");
        this.supportedFrames.add("TALB");
        this.supportedFrames.add("TSOA");
        this.supportedFrames.add("TPE1");
        this.supportedFrames.add("APIC");
        this.supportedFrames.add("AENC");
        this.supportedFrames.add(FRAME_ID_AUDIO_SEEK_POINT_INDEX);
        this.supportedFrames.add("TBPM");
        this.supportedFrames.add("CHAP");
        this.supportedFrames.add("CTOC");
        this.supportedFrames.add("COMM");
        this.supportedFrames.add("COMR");
        this.supportedFrames.add("TCOM");
        this.supportedFrames.add("TPE3");
        this.supportedFrames.add("TIT1");
        this.supportedFrames.add("TCOP");
        this.supportedFrames.add("TENC");
        this.supportedFrames.add(FRAME_ID_ENCODING_TIME);
        this.supportedFrames.add("ENCR");
        this.supportedFrames.add(FRAME_ID_EQUALISATION2);
        this.supportedFrames.add("ETCO");
        this.supportedFrames.add("TOWN");
        this.supportedFrames.add("TFLT");
        this.supportedFrames.add("GEOB");
        this.supportedFrames.add("TCON");
        this.supportedFrames.add("GRID");
        this.supportedFrames.add("TSSE");
        this.supportedFrames.add("TKEY");
        this.supportedFrames.add(FRAME_ID_INVOLVED_PEOPLE);
        this.supportedFrames.add("TSRC");
        this.supportedFrames.add("GRP1");
        this.supportedFrames.add("TLAN");
        this.supportedFrames.add("TLEN");
        this.supportedFrames.add("LINK");
        this.supportedFrames.add("TEXT");
        this.supportedFrames.add("TMED");
        this.supportedFrames.add(FRAME_ID_MOOD);
        this.supportedFrames.add("MVNM");
        this.supportedFrames.add("MVIN");
        this.supportedFrames.add("MLLT");
        this.supportedFrames.add("MCDI");
        this.supportedFrames.add(FRAME_ID_MUSICIAN_CREDITS);
        this.supportedFrames.add("TOPE");
        this.supportedFrames.add(FRAME_ID_ORIGINAL_RELEASE_TIME);
        this.supportedFrames.add("TOFN");
        this.supportedFrames.add("TOLY");
        this.supportedFrames.add("TOAL");
        this.supportedFrames.add("OWNE");
        this.supportedFrames.add("TSOP");
        this.supportedFrames.add("TDLY");
        this.supportedFrames.add("PCNT");
        this.supportedFrames.add("POPM");
        this.supportedFrames.add("POSS");
        this.supportedFrames.add("PRIV");
        this.supportedFrames.add(FRAME_ID_PRODUCED_NOTICE);
        this.supportedFrames.add("TPUB");
        this.supportedFrames.add("TRSN");
        this.supportedFrames.add("TRSO");
        this.supportedFrames.add("RBUF");
        this.supportedFrames.add(FRAME_ID_RELATIVE_VOLUME_ADJUSTMENT2);
        this.supportedFrames.add(FRAME_ID_RELEASE_TIME);
        this.supportedFrames.add("TPE4");
        this.supportedFrames.add("RVRB");
        this.supportedFrames.add(FRAME_ID_SEEK);
        this.supportedFrames.add("TPOS");
        this.supportedFrames.add("TSST");
        this.supportedFrames.add(FRAME_ID_SIGNATURE);
        this.supportedFrames.add("SYLT");
        this.supportedFrames.add("SYTC");
        this.supportedFrames.add(FRAME_ID_TAGGING_TIME);
        this.supportedFrames.add("USER");
        this.supportedFrames.add("TIT2");
        this.supportedFrames.add("TIT3");
        this.supportedFrames.add("TSOT");
        this.supportedFrames.add("TRCK");
        this.supportedFrames.add("UFID");
        this.supportedFrames.add("USLT");
        this.supportedFrames.add("WOAR");
        this.supportedFrames.add("WCOM");
        this.supportedFrames.add("WCOP");
        this.supportedFrames.add("WOAF");
        this.supportedFrames.add("WORS");
        this.supportedFrames.add("WPAY");
        this.supportedFrames.add("WPUB");
        this.supportedFrames.add("WOAS");
        this.supportedFrames.add("TXXX");
        this.supportedFrames.add("WXXX");
        this.supportedFrames.add(FRAME_ID_YEAR);
        this.extensionFrames.add("TCMP");
        this.extensionFrames.add("TSO2");
        this.extensionFrames.add("TSOC");
        this.commonFrames.add("TPE1");
        this.commonFrames.add("TALB");
        this.commonFrames.add("TIT2");
        this.commonFrames.add("TCON");
        this.commonFrames.add("TRCK");
        this.commonFrames.add(FRAME_ID_YEAR);
        this.commonFrames.add("COMM");
        this.binaryFrames.add("APIC");
        this.binaryFrames.add("AENC");
        this.binaryFrames.add("ENCR");
        this.binaryFrames.add(FRAME_ID_EQUALISATION2);
        this.binaryFrames.add("ETCO");
        this.binaryFrames.add("GEOB");
        this.binaryFrames.add(FRAME_ID_RELATIVE_VOLUME_ADJUSTMENT2);
        this.binaryFrames.add("RBUF");
        this.binaryFrames.add("UFID");
        this.idToValue.put("TPE2", "Text: Band/Orchestra/Accompaniment");
        this.idToValue.put("TALB", "Text: Album/Movie/Show title");
        this.idToValue.put("TSOA", "Album sort order");
        this.idToValue.put("TPE1", "Text: Lead artist(s)/Lead performer(s)/Soloist(s)/Performing group");
        this.idToValue.put("APIC", "Attached picture");
        this.idToValue.put("AENC", "Audio encryption");
        this.idToValue.put(FRAME_ID_AUDIO_SEEK_POINT_INDEX, "Audio seek point index");
        this.idToValue.put("TBPM", "Text: BPM (Beats Per Minute)");
        this.idToValue.put("CHAP", "Chapter");
        this.idToValue.put("CTOC", "Chapter TOC");
        this.idToValue.put("COMM", "Comments");
        this.idToValue.put("COMR", "Commercial Frame");
        this.idToValue.put("TCOM", "Text: Composer");
        this.idToValue.put("TPE3", "Text: Conductor/Performer refinement");
        this.idToValue.put("TIT1", "Text: Content group description");
        this.idToValue.put("TCOP", "Text: Copyright message");
        this.idToValue.put("TENC", "Text: Encoded by");
        this.idToValue.put(FRAME_ID_ENCODING_TIME, "Text: Encoding time");
        this.idToValue.put("ENCR", "Encryption method registration");
        this.idToValue.put(FRAME_ID_EQUALISATION2, "Equalization (2)");
        this.idToValue.put("ETCO", "Event timing codes");
        this.idToValue.put("TOWN", "Text:File Owner");
        this.idToValue.put("TFLT", "Text: File type");
        this.idToValue.put("GEOB", "General encapsulated datatype");
        this.idToValue.put("TCON", "Text: Content type");
        this.idToValue.put("GRID", "Group ID Registration");
        this.idToValue.put("TSSE", "Text: Software/hardware and settings used for encoding");
        this.idToValue.put("TKEY", "Text: Initial key");
        this.idToValue.put(FRAME_ID_INVOLVED_PEOPLE, "Involved people list");
        this.idToValue.put("TSRC", "Text: ISRC (International Standard Recording Code)");
        this.idToValue.put("GRP1", "iTunes Grouping");
        this.idToValue.put("TLAN", "Text: Language(s)");
        this.idToValue.put("TLEN", "Text: Length");
        this.idToValue.put("LINK", "Linked information");
        this.idToValue.put("TEXT", "Text: Lyricist/text writer");
        this.idToValue.put("TMED", "Text: Media type");
        this.idToValue.put(FRAME_ID_MOOD, "Text: Mood");
        this.idToValue.put("MVNM", "Text: Movement");
        this.idToValue.put("MVIN", "Text: Movement No");
        this.idToValue.put("MLLT", "MPEG location lookup table");
        this.idToValue.put("MCDI", "Music CD Identifier");
        this.idToValue.put("TOPE", "Text: Original artist(s)/performer(s)");
        this.idToValue.put(FRAME_ID_ORIGINAL_RELEASE_TIME, "Text: Original release time");
        this.idToValue.put("TOFN", "Text: Original filename");
        this.idToValue.put("TOLY", "Text: Original Lyricist(s)/text writer(s)");
        this.idToValue.put("TOAL", "Text: Original album/Movie/Show title");
        this.idToValue.put("OWNE", "Ownership");
        this.idToValue.put("TSOP", "Performance Sort Order");
        this.idToValue.put("TDLY", "Text: Playlist delay");
        this.idToValue.put("PCNT", "Play counter");
        this.idToValue.put("POPM", "Popularimeter");
        this.idToValue.put("POSS", "Position Sync");
        this.idToValue.put("PRIV", "Private frame");
        this.idToValue.put(FRAME_ID_PRODUCED_NOTICE, "Produced Notice");
        this.idToValue.put("TPUB", "Text: Publisher");
        this.idToValue.put("TRSN", "Text: Radio Name");
        this.idToValue.put("TRSO", "Text: Radio Owner");
        this.idToValue.put("RBUF", "Recommended buffer size");
        this.idToValue.put(FRAME_ID_RELATIVE_VOLUME_ADJUSTMENT2, "Relative volume adjustment(2)");
        this.idToValue.put(FRAME_ID_RELEASE_TIME, "Release Time");
        this.idToValue.put("TPE4", "Text: Interpreted, remixed, or otherwise modified by");
        this.idToValue.put("RVRB", "Reverb");
        this.idToValue.put(FRAME_ID_SEEK, "Seek");
        this.idToValue.put("TPOS", "Text: Part of a setField");
        this.idToValue.put("TSST", "Text: Set subtitle");
        this.idToValue.put(FRAME_ID_SIGNATURE, DataTypes.OBJ_SIGNATURE);
        this.idToValue.put("SYLT", "Synchronized lyric/text");
        this.idToValue.put("SYTC", "Synced tempo codes");
        this.idToValue.put(FRAME_ID_TAGGING_TIME, "Text: Tagging time");
        this.idToValue.put("USER", "Terms of Use");
        this.idToValue.put("TIT2", "Text: title");
        this.idToValue.put("TIT3", "Text: Subtitle/Description refinement");
        this.idToValue.put("TSOT", "Text: title sort order");
        this.idToValue.put("TRCK", "Text: Track number/Position in setField");
        this.idToValue.put("UFID", "Unique file identifier");
        this.idToValue.put("USLT", "Unsychronized lyric/text transcription");
        this.idToValue.put("WOAR", "URL: Official artist/performer webpage");
        this.idToValue.put("WCOM", "URL: Commercial information");
        this.idToValue.put("WCOP", "URL: Copyright/Legal information");
        this.idToValue.put("WOAF", "URL: Official audio file webpage");
        this.idToValue.put("WORS", "URL: Official Radio website");
        this.idToValue.put("WPAY", "URL: Payment for this recording ");
        this.idToValue.put("WPUB", "URL: Publishers official webpage");
        this.idToValue.put("WOAS", "URL: Official audio source webpage");
        this.idToValue.put("TXXX", "User defined text information frame");
        this.idToValue.put("WXXX", "User defined URL link frame");
        this.idToValue.put(FRAME_ID_YEAR, "Text:Year");
        this.idToValue.put("TCMP", "Is Compilation");
        this.idToValue.put("TSO2", "Text:Album Artist Sort Order Frame");
        this.idToValue.put("TSOC", "Text:Composer Sort Order Frame");
        createMaps();
        this.multipleFrames.add("TXXX");
        this.multipleFrames.add("WXXX");
        this.multipleFrames.add("APIC");
        this.multipleFrames.add("PRIV");
        this.multipleFrames.add("COMM");
        this.multipleFrames.add("UFID");
        this.multipleFrames.add("USLT");
        this.multipleFrames.add("POPM");
        this.multipleFrames.add("GEOB");
        this.multipleFrames.add("WOAR");
        this.multipleFrames.add(FRAME_ID_RELATIVE_VOLUME_ADJUSTMENT2);
        this.discardIfFileAlteredFrames.add("ETCO");
        this.discardIfFileAlteredFrames.add("MLLT");
        this.discardIfFileAlteredFrames.add("POSS");
        this.discardIfFileAlteredFrames.add("SYLT");
        this.discardIfFileAlteredFrames.add("SYTC");
        this.discardIfFileAlteredFrames.add("ETCO");
        this.discardIfFileAlteredFrames.add("TENC");
        this.discardIfFileAlteredFrames.add("TLEN");
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ACOUSTID_FINGERPRINT, (FieldKey) ID3v24FieldKey.ACOUSTID_FINGERPRINT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ACOUSTID_ID, (FieldKey) ID3v24FieldKey.ACOUSTID_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ALBUM, (FieldKey) ID3v24FieldKey.ALBUM);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ALBUM_ARTIST, (FieldKey) ID3v24FieldKey.ALBUM_ARTIST);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ALBUM_ARTIST_SORT, (FieldKey) ID3v24FieldKey.ALBUM_ARTIST_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ALBUM_ARTISTS, (FieldKey) ID3v24FieldKey.ALBUM_ARTISTS);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ALBUM_ARTISTS_SORT, (FieldKey) ID3v24FieldKey.ALBUM_ARTISTS_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ALBUM_SORT, (FieldKey) ID3v24FieldKey.ALBUM_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ALBUM_YEAR, (FieldKey) ID3v24FieldKey.ALBUM_YEAR);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.AMAZON_ID, (FieldKey) ID3v24FieldKey.AMAZON_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ARRANGER, (FieldKey) ID3v24FieldKey.ARRANGER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ARRANGER_SORT, (FieldKey) ID3v24FieldKey.ARRANGER_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ARTIST, (FieldKey) ID3v24FieldKey.ARTIST);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ARTISTS, (FieldKey) ID3v24FieldKey.ARTISTS);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ARTISTS_SORT, (FieldKey) ID3v24FieldKey.ARTISTS_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ARTIST_SORT, (FieldKey) ID3v24FieldKey.ARTIST_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.AUDIO_ENGINEER, (FieldKey) ID3v24FieldKey.AUDIO_ENGINEER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.AUDIO_ENGINEER_SORT, (FieldKey) ID3v24FieldKey.AUDIO_ENGINEER_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.BALANCE_ENGINEER, (FieldKey) ID3v24FieldKey.BALANCE_ENGINEER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.BALANCE_ENGINEER_SORT, (FieldKey) ID3v24FieldKey.BALANCE_ENGINEER_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.BARCODE, (FieldKey) ID3v24FieldKey.BARCODE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.BPM, (FieldKey) ID3v24FieldKey.BPM);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CATALOG_NO, (FieldKey) ID3v24FieldKey.CATALOG_NO);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CHOIR, (FieldKey) ID3v24FieldKey.CHOIR);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CHOIR_SORT, (FieldKey) ID3v24FieldKey.CHOIR_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CLASSICAL_CATALOG, (FieldKey) ID3v24FieldKey.CLASSICAL_CATALOG);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CLASSICAL_NICKNAME, (FieldKey) ID3v24FieldKey.CLASSICAL_NICKNAME);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.COMMENT, (FieldKey) ID3v24FieldKey.COMMENT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.COMPOSER, (FieldKey) ID3v24FieldKey.COMPOSER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.COMPOSER_SORT, (FieldKey) ID3v24FieldKey.COMPOSER_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CONDUCTOR, (FieldKey) ID3v24FieldKey.CONDUCTOR);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CONDUCTOR_SORT, (FieldKey) ID3v24FieldKey.CONDUCTOR_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.COPYRIGHT, (FieldKey) ID3v24FieldKey.COPYRIGHT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.COUNTRY, (FieldKey) ID3v24FieldKey.COUNTRY);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.COVER_ART, (FieldKey) ID3v24FieldKey.COVER_ART);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CREDITS, (FieldKey) ID3v24FieldKey.CREDITS);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CUSTOM1, (FieldKey) ID3v24FieldKey.CUSTOM1);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CUSTOM2, (FieldKey) ID3v24FieldKey.CUSTOM2);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CUSTOM3, (FieldKey) ID3v24FieldKey.CUSTOM3);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CUSTOM4, (FieldKey) ID3v24FieldKey.CUSTOM4);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.CUSTOM5, (FieldKey) ID3v24FieldKey.CUSTOM5);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.DISC_NO, (FieldKey) ID3v24FieldKey.DISC_NO);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.DISC_SUBTITLE, (FieldKey) ID3v24FieldKey.DISC_SUBTITLE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.DISC_TOTAL, (FieldKey) ID3v24FieldKey.DISC_NO);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.DJMIXER, (FieldKey) ID3v24FieldKey.DJMIXER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.DJMIXER_SORT, (FieldKey) ID3v24FieldKey.DJMIXER_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOOD_ELECTRONIC, (FieldKey) ID3v24FieldKey.MOOD_ELECTRONIC);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ENCODER, (FieldKey) ID3v24FieldKey.ENCODER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ENGINEER, (FieldKey) ID3v24FieldKey.ENGINEER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ENGINEER_SORT, (FieldKey) ID3v24FieldKey.ENGINEER_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ENSEMBLE, (FieldKey) ID3v24FieldKey.ENSEMBLE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ENSEMBLE_SORT, (FieldKey) ID3v24FieldKey.ENSEMBLE_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.FBPM, (FieldKey) ID3v24FieldKey.FBPM);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.GENRE, (FieldKey) ID3v24FieldKey.GENRE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.GROUP, (FieldKey) ID3v24FieldKey.GROUP);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.GROUPING, (FieldKey) ID3v24FieldKey.GROUPING);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.INSTRUMENT, (FieldKey) ID3v24FieldKey.INSTRUMENT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.INVOLVEDPEOPLE, (FieldKey) ID3v24FieldKey.INVOLVED_PEOPLE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.IPI, (FieldKey) ID3v24FieldKey.IPI);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ISRC, (FieldKey) ID3v24FieldKey.ISRC);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ISWC, (FieldKey) ID3v24FieldKey.ISWC);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.IS_CLASSICAL, (FieldKey) ID3v24FieldKey.IS_CLASSICAL);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.IS_COMPILATION, (FieldKey) ID3v24FieldKey.IS_COMPILATION);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.IS_SOUNDTRACK, (FieldKey) ID3v24FieldKey.IS_SOUNDTRACK);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.IS_GREATEST_HITS, (FieldKey) ID3v24FieldKey.IS_GREATEST_HITS);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.IS_HD, (FieldKey) ID3v24FieldKey.IS_HD);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.IS_LIVE, (FieldKey) ID3v24FieldKey.IS_LIVE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ITUNES_GROUPING, (FieldKey) ID3v24FieldKey.ITUNES_GROUPING);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.JAIKOZ_ID, (FieldKey) ID3v24FieldKey.JAIKOZ_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.KEY, (FieldKey) ID3v24FieldKey.KEY);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.LANGUAGE, (FieldKey) ID3v24FieldKey.LANGUAGE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.LYRICIST, (FieldKey) ID3v24FieldKey.LYRICIST);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.LYRICIST_SORT, (FieldKey) ID3v24FieldKey.LYRICIST_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.LYRICS, (FieldKey) ID3v24FieldKey.LYRICS);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MASTERING, (FieldKey) ID3v24FieldKey.MASTERING);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MASTERING_SORT, (FieldKey) ID3v24FieldKey.MASTERING_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MEDIA, (FieldKey) ID3v24FieldKey.MEDIA);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MIXER, (FieldKey) ID3v24FieldKey.MIXER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MIXER_SORT, (FieldKey) ID3v24FieldKey.MIXER_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOOD, (FieldKey) ID3v24FieldKey.MOOD);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOOD_ACOUSTIC, (FieldKey) ID3v24FieldKey.MOOD_ACOUSTIC);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOOD_AGGRESSIVE, (FieldKey) ID3v24FieldKey.MOOD_AGGRESSIVE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOOD_AROUSAL, (FieldKey) ID3v24FieldKey.MOOD_AROUSAL);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOOD_DANCEABILITY, (FieldKey) ID3v24FieldKey.MOOD_DANCEABILITY);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOOD_HAPPY, (FieldKey) ID3v24FieldKey.MOOD_HAPPY);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOOD_INSTRUMENTAL, (FieldKey) ID3v24FieldKey.MOOD_INSTRUMENTAL);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOOD_PARTY, (FieldKey) ID3v24FieldKey.MOOD_PARTY);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOOD_RELAXED, (FieldKey) ID3v24FieldKey.MOOD_RELAXED);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOOD_SAD, (FieldKey) ID3v24FieldKey.MOOD_SAD);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOOD_VALENCE, (FieldKey) ID3v24FieldKey.MOOD_VALENCE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOVEMENT, (FieldKey) ID3v24FieldKey.MOVEMENT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOVEMENT_NO, (FieldKey) ID3v24FieldKey.MOVEMENT_NO);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MOVEMENT_TOTAL, (FieldKey) ID3v24FieldKey.MOVEMENT_TOTAL);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_ARTISTID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_ARTISTID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_DISC_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_DISC_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_ORIGINAL_RELEASE_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_ORIGINAL_RELEASEID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_RELEASEARTISTID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_RELEASEARTISTID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_RELEASEID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_RELEASEID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_RELEASE_COUNTRY, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_RELEASE_COUNTRY);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_RELEASE_GROUP_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_RELEASE_GROUP_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_RELEASE_STATUS, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_RELEASE_STATUS);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_RELEASE_TRACK_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_RELEASE_TRACK_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_RELEASE_TYPE, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_RELEASE_TYPE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_TRACK_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_TRACK_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_WORK);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_WORK_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_RECORDING_WORK, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_RECORDING_WORK);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_RECORDING_WORK_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_RECORDING_WORK_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_ID, (FieldKey) ID3v24FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICIP_ID, (FieldKey) ID3v24FieldKey.MUSICIP_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.OCCASION, (FieldKey) ID3v24FieldKey.OCCASION);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.OPUS, (FieldKey) ID3v24FieldKey.OPUS);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ORCHESTRA, (FieldKey) ID3v24FieldKey.ORCHESTRA);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ORCHESTRA_SORT, (FieldKey) ID3v24FieldKey.ORCHESTRA_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ORIGINAL_ALBUM, (FieldKey) ID3v24FieldKey.ORIGINAL_ALBUM);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ORIGINALRELEASEDATE, (FieldKey) ID3v24FieldKey.ORIGINALRELEASEDATE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ORIGINAL_ARTIST, (FieldKey) ID3v24FieldKey.ORIGINAL_ARTIST);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ORIGINAL_LYRICIST, (FieldKey) ID3v24FieldKey.ORIGINAL_LYRICIST);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ORIGINAL_YEAR, (FieldKey) ID3v24FieldKey.ORIGINAL_YEAR);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.OVERALL_WORK, (FieldKey) ID3v24FieldKey.OVERALL_WORK);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.PART, (FieldKey) ID3v24FieldKey.PART);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.PART_NUMBER, (FieldKey) ID3v24FieldKey.PART_NUMBER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.PART_TYPE, (FieldKey) ID3v24FieldKey.PART_TYPE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.PERFORMER, (FieldKey) ID3v24FieldKey.PERFORMER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.PERFORMER_NAME, (FieldKey) ID3v24FieldKey.PERFORMER_NAME);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.PERFORMER_NAME_SORT, (FieldKey) ID3v24FieldKey.PERFORMER_NAME_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.PERIOD, (FieldKey) ID3v24FieldKey.PERIOD);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.PRODUCER, (FieldKey) ID3v24FieldKey.PRODUCER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.PRODUCER_SORT, (FieldKey) ID3v24FieldKey.PRODUCER_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.QUALITY, (FieldKey) ID3v24FieldKey.QUALITY);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.RANKING, (FieldKey) ID3v24FieldKey.RANKING);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.RATING, (FieldKey) ID3v24FieldKey.RATING);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.RECORDING_ENGINEER, (FieldKey) ID3v24FieldKey.RECORDING_ENGINEER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.RECORDING_ENGINEER_SORT, (FieldKey) ID3v24FieldKey.RECORDING_ENGINEER_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.RECORD_LABEL, (FieldKey) ID3v24FieldKey.RECORD_LABEL);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.RECORDINGDATE, (FieldKey) ID3v24FieldKey.RECORDINGDATE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.RECORDINGSTARTDATE, (FieldKey) ID3v24FieldKey.RECORDINGSTARTDATE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.RECORDINGENDDATE, (FieldKey) ID3v24FieldKey.RECORDINGENDDATE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.RECORDINGLOCATION, (FieldKey) ID3v24FieldKey.RECORDINGLOCATION);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.REMIXER, (FieldKey) ID3v24FieldKey.REMIXER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ROONALBUMTAG, (FieldKey) ID3v24FieldKey.ROONALBUMTAG);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.ROONTRACKTAG, (FieldKey) ID3v24FieldKey.ROONTRACKTAG);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.SCRIPT, (FieldKey) ID3v24FieldKey.SCRIPT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.SECTION, (FieldKey) ID3v24FieldKey.SECTION);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.SINGLE_DISC_TRACK_NO, (FieldKey) ID3v24FieldKey.SINGLE_DISC_TRACK_NO);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.SONGKONG_ID, (FieldKey) ID3v24FieldKey.SONGKONG_ID);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.SOUND_ENGINEER, (FieldKey) ID3v24FieldKey.SOUND_ENGINEER);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.SOUND_ENGINEER_SORT, (FieldKey) ID3v24FieldKey.SOUND_ENGINEER_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.SUBTITLE, (FieldKey) ID3v24FieldKey.SUBTITLE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.TAGS, (FieldKey) ID3v24FieldKey.TAGS);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.TEMPO, (FieldKey) ID3v24FieldKey.TEMPO);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.TIMBRE, (FieldKey) ID3v24FieldKey.TIMBRE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.TITLE, (FieldKey) ID3v24FieldKey.TITLE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.TITLE_MOVEMENT, (FieldKey) ID3v24FieldKey.TITLE_MOVEMENT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.TITLE_SORT, (FieldKey) ID3v24FieldKey.TITLE_SORT);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.TONALITY, (FieldKey) ID3v24FieldKey.TONALITY);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.TRACK, (FieldKey) ID3v24FieldKey.TRACK);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.TRACK_TOTAL, (FieldKey) ID3v24FieldKey.TRACK_TOTAL);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.URL_BANDCAMP_ARTIST_SITE, (FieldKey) ID3v24FieldKey.URL_BANDCAMP_ARTIST_SITE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.URL_BANDCAMP_RELEASE_SITE, (FieldKey) ID3v24FieldKey.URL_BANDCAMP_RELEASE_SITE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.URL_DISCOGS_ARTIST_SITE, (FieldKey) ID3v24FieldKey.URL_DISCOGS_ARTIST_SITE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.URL_DISCOGS_RELEASE_SITE, (FieldKey) ID3v24FieldKey.URL_DISCOGS_RELEASE_SITE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.URL_LYRICS_SITE, (FieldKey) ID3v24FieldKey.URL_LYRICS_SITE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.URL_OFFICIAL_ARTIST_SITE, (FieldKey) ID3v24FieldKey.URL_OFFICIAL_ARTIST_SITE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.URL_OFFICIAL_RELEASE_SITE, (FieldKey) ID3v24FieldKey.URL_OFFICIAL_RELEASE_SITE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.URL_WIKIPEDIA_ARTIST_SITE, (FieldKey) ID3v24FieldKey.URL_WIKIPEDIA_ARTIST_SITE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.URL_WIKIPEDIA_RELEASE_SITE, (FieldKey) ID3v24FieldKey.URL_WIKIPEDIA_RELEASE_SITE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.WORK, (FieldKey) ID3v24FieldKey.WORK);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1, (FieldKey) ID3v24FieldKey.WORK_PART_LEVEL1);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_TYPE, (FieldKey) ID3v24FieldKey.WORK_PART_LEVEL1_TYPE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2, (FieldKey) ID3v24FieldKey.WORK_PART_LEVEL2);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_TYPE, (FieldKey) ID3v24FieldKey.WORK_PART_LEVEL2_TYPE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3, (FieldKey) ID3v24FieldKey.WORK_PART_LEVEL3);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_TYPE, (FieldKey) ID3v24FieldKey.WORK_PARTOF_LEVEL3_TYPE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4, (FieldKey) ID3v24FieldKey.WORK_PART_LEVEL4);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_TYPE, (FieldKey) ID3v24FieldKey.WORK_PART_LEVEL4_TYPE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5, (FieldKey) ID3v24FieldKey.WORK_PART_LEVEL5);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_TYPE, (FieldKey) ID3v24FieldKey.WORK_PART_LEVEL5_TYPE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6, (FieldKey) ID3v24FieldKey.WORK_PART_LEVEL6);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_TYPE, (FieldKey) ID3v24FieldKey.WORK_PART_LEVEL6_TYPE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.VERSION, (FieldKey) ID3v24FieldKey.VERSION);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.WORK_TYPE, (FieldKey) ID3v24FieldKey.WORK_TYPE);
        this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.YEAR, (FieldKey) ID3v24FieldKey.YEAR);
        populateId3ToTagField();
    }

    private void populateId3ToTagField() {
        Iterator it = this.tagFieldToId3.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry entry = (Map.Entry) it.next();
            this.id3ToTagField.put((EnumMap<ID3v24FieldKey, FieldKey>) entry.getValue(), (ID3v24FieldKey) entry.getKey());
        }
    }

    @Override // org.jaudiotagger.tag.id3.ID3Frames
    public void setITunes12_6WorkGroupingMode(boolean z) {
        if (z) {
            this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.WORK, (FieldKey) ID3v24FieldKey.GROUPING);
            this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.GROUPING, (FieldKey) ID3v24FieldKey.ITUNES_GROUPING);
        } else {
            this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.WORK, (FieldKey) ID3v24FieldKey.WORK);
            this.tagFieldToId3.put((EnumMap<FieldKey, ID3v24FieldKey>) FieldKey.GROUPING, (FieldKey) ID3v24FieldKey.GROUPING);
        }
        populateId3ToTagField();
    }

    public ID3v24FieldKey getId3KeyFromGenericKey(FieldKey fieldKey) {
        return this.tagFieldToId3.get(fieldKey);
    }

    public FieldKey getGenericKeyFromId3(ID3v24FieldKey iD3v24FieldKey) {
        return this.id3ToTagField.get(iD3v24FieldKey);
    }
}
